/*
 * Copyright 2015 David Laurell
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.daverix.eclipselibraryplugin
import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction

public class GenerateEclipseProjectPropertiesFileTask extends DefaultTask {
    def references
    def targetSdkVersion
    def destinationDir

    @TaskAction
    def generateFile() {
        if(references == null) return
        if(destinationDir == null) return

        def file = project.file("$destinationDir/project.properties")
        file.text = "# This file is automatically generated by EclipseLibraryPlugin.\n" +
                "# Do not modify this file -- YOUR CHANGES WILL BE ERASED!\n" +
                "\n" +
                "# Project target.\n" +
                "target=android-$targetSdkVersion\n" +
                "android.library=true\n"
        for(String reference : references) {
            file.text += "android.library.reference.1=$reference\n"
        }
    }
}
