package net.daverix.eclipseplugin
import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction

public class GenerateEclipseProjectPropertiesFileTask extends DefaultTask {
    String[] references
    int targetSdkVersion
    File destinationDir

    @TaskAction
    def generateFile() {
        if(references == null) return
        if(destinationDir == null) return

        def file = new File(destinationDir, "project.properties")
        file.text = "# This file is automatically generated by CreateEclipseReleasePlugin.\n" +
                "# Do not modify this file -- YOUR CHANGES WILL BE ERASED!\n" +
                "\n" +
                "# Project target.\n" +
                "target=android-$targetSdkVersion\n" +
                "android.library=true\n"
        for(String reference : references) {
            file.text += "android.library.reference.1=$reference\n"
        }
    }
}
